### ISSUE TITLE
IDEA: Is it possible to implement an evolution modifier?

### ISSUE THREAD

**Issue by Mooshroomdude250** [semaj14/Multi-PokemonFramework#8]
This addon (along with PKSM) really spice things up for Pokémon once you've beaten the game, but I thought if it was possible, to add an evolution modifier where Pokémon can evolve into another Pokémon that they normally can't (such as Ekans evolving into Vaporeon for example). Is this possible? If so, then thanks in advance!

**Comment by semaj14** [comment]
I don't really see a point when you could just use the built-in editor to modify the species. However, it would be kind of cool to implement that, but for now, I don't see the point.
