### ISSUE TITLE
[Feature Request] Gen1/2 Support

### ISSUE THREAD

**Issue by Ninjistix** [semaj14/Multi-PokemonFramework#9]
Requesting  possible gen 1/2 support

List of games include but are not limited to
Red / Blue / Yellow
Gold / Silver / Crystal

**Comment by TwystedXYZ** [comment]
Would indeed be greatly appreciated.

**Comment by semaj14** [comment]
Sorry, maybe in a separate plugin, this plugin is already a huge project itself, considering I'm the only dev here.
